### ISSUE TITLE
Scrollbars shown due to language lists

### ISSUE THREAD

**Issue by MarceloRuiz** [philer/MDModern#3]
Hi Philipp, 
I guess the old bug is back. Just updated to mint 17.2 and the scrollbars appeared again in the login screen.
Maybe is because of the long language list (I do have English and Spanish languages installed.
Thanks!

**Comment by philer** [comment]
Hm, thanks for letting me know. I haven't upgraded yet, I'll look into it when I have. It's probably going to be a month or so, sorry for the wait.

**Comment by philer** [comment]
So turns out the changes I made never made it into the official repository, so almost a year later linux mint doesn't actually ship with the shipped version.  For some reason I closed the pull request because I thought it had become obsolete. I'll submit a new one after I do a bit more testing. It might take a little bit to get accepted so if you want the fixed version now you might have to install the theme manually from here.
