### ISSUE TITLE
Background image doens't display on login screen

### ISSUE THREAD

**Issue by jvaldezjr1** [philer/MDModern#8]
I've followed your instructions, but I can't get the background image to display properly.  I'm running archlinux, and have MDM setup properly.  When I run MDM setup, it allows me select your theme.  When I boot the machine, MDModern appears, and there is a black background displayed.    I changed the default slideshow file to 'slideshow.conf' and I changed the following values in that file:

fill_style = cover

I also added a filepath file:///my_wallpaper_directory/my_image

Any suggestions?

**Comment by philer** [comment]
Did you put quotes around "cover"? It needs to be a json compatible string, so the line should be
`fill_style = "cover"`.

Other than that, maybe check the file permissions for that wallpaper? If I remember correctly the login screen isn't run as root so you'll have to give read permissions for all on your wallpaper.

**Comment by jvaldezjr1** [comment]
Yup, tried both of those things, still won't display.

**Comment by philer** [comment]
Hm, other than file permissions I can't really think of much. Just to be sure, the rest does work? I.e. can you log in using the theme?

You could try opening the theme's index.html in your browser, see if it works there (the slideshow should work independently of the rest). That should simplify testing.

I've occasionally had issues with extremely large wallpapers, maybe the file is too big? Try different images (though I'd guess you've already tried that).

Otherwise maybe post your config so I can check it out…

**Comment by jvaldezjr1** [comment]
Everything works but displaying the wallpaper. I've messed around some with the slideshow.config file a bunch.  I tried loading the html file too, and no background displayed either.  I also tried using the screenshot image in the directory with no luck.
[slideshow.txt](https://github.com/philer/MDModern/files/96096/slideshow.txt)

**Comment by philer** [comment]
Okay this is a little obscure: The [background](https://developer.mozilla.org/en-US/docs/Web/CSS/background) shorthand property in css doesn't allow a [background-size](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size) without a [background-position](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position). Looking at the formal syntax the background-size (in your case "cover") may only follow after a background-position, separated by a slash.

So you'd have to use something like "center / cover" to make it work.

With the incorrect value the entire background property (image + fill_style) ends up being invalid and is ignored.

This is a little mean because in my example I even suggested using "repeat", which actually works because background-repeat is a separate css property that doesn't require a background-position when used in the combined shorthand. If you're not familiar with the exact formal syntax it's fair to assume that if "repeat" works "cover" should as well. I might try to think of some better examples but in the end the syntax for that css shorthand just kinda sucks.
I should also split of the background-image so it'll at least still work with an incorrect fill_style.

**Comment by jvaldezjr1** [comment]
I see...Beautiful... So I replaced the `"fill_style"` property with `background = "center / cover"` and it's working now.  We should probably capture this in the comments for the `default-slideshow.conf` file.  I'm running Archlinux with this, so I'll look around at the documentation there and note this in the package wiki or link back to this issue.  Closing this also.  Thanks for the help!

**Comment by jvaldezjr1** [comment]
Heh...I spoke too soon.  So when I load index.html into the browser, the slideshow works.  However, when I restart my display manager and log back in, it does not display.

**Comment by jvaldezjr1** [comment]
Ok I fixed it now.  It was a combo of that code I posted above, and I somehow screwed up the permissions.  I ended up copying the wallpapers I wanted into the mdmodern directory, and granting 666 permissions on those files.

That said, this is a beautiful greeter!  Now if I can move the credential box...

**Comment by philer** [comment]
>  Now if I can move the credential box...

You can if you install the necessary dependencies to compile [less](http://lesscss.org/). You could either install only less (I'm not on Arch but I'm sure there's a package in the AUR. In the Debian repos it's called lessc). Or you can install nodejs + npm and then run `npm instsall` followed by `grunt` to build everything at once.

Once you have the build process you can simply edit the positioning in [login.less](https://github.com/philer/MDModern/blob/master/less/login.less#L30).
